# File: .github/workflows/node.js.yml
name: SvRemind CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Yarn
        run: npm install -g yarn

      # Build Backend (NestJS)
      - name: Install Dependencies Backend
        run: |
          cd backend
          yarn install
          yarn build
      - name: Copy Backend files
        run: |
          cd backend
          mkdir ./dist_folder
          cp -rf ./dist ./.env ./package.json ./dist_folder
      - name: Upload Backend artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-backend
          path: backend/dist_folder

      # Build Frontend (NextJS)
      - name: Install Dependencies and Build Frontend
        run: |
          cd frontend
          yarn install
          yarn build
      - name: Upload Frontend artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-frontend
          path: frontend/out  # NextJS build output directory (adjust if using a different output dir)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Frontend artifacts
        uses: actions/download-artifact@v4  # Ensure download-artifact is also updated to v4
        with:
          name: build-frontend
          path: frontend/out

      - name: Download Backend artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: build-backend
          path: backend/dist_folder

      # WSL deployment: Manual step (since SSH is not needed)
      - name: Deploy to WSL
        run: |
          echo "Artifacts are ready for deployment to WSL."
          echo "Manually copy artifacts to WSL and run deployment commands."
