name: SvRemind CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Yarn
        run: npm install -g yarn

      # Build Backend (NestJS)
      - name: Install Dependencies Backend
        run: |
          cd backend
          yarn install
          yarn build
      - name: Copy Backend files
        run: |
          cd backend
          mkdir ./dist_folder
          cp -rf ./dist ./.env ./package.json ./dist_folder
      - name: Upload Backend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-backend
          path: backend/dist_folder

      # Build Frontend (NextJS)
      - name: Install Dependencies and Build Frontend
        run: |
          cd frontend
          yarn install
          yarn build
      - name: Upload Frontend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-frontend
          path: frontend/out  # NextJS build output directory (adjust if using a different output dir)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Frontend artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-frontend
          path: frontend/out

      - name: Download Backend artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-backend
          path: backend/dist_folder

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SERVER_SECRET_KEY }}
          script: |
            ssh-add -D
            ssh-add ${{ secrets.SERVER_SECRET_KEY }}
            ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /var/www/svremind/frontend && rm -rf ./**"
          scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -r frontend/out/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/svremind/frontend

      - name: Deploy Backend
        run: |
          scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -r backend/dist_folder/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/svremind/backend
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /var/www/svremind/backend && yarn install && pm2 stop svremind-backend && pm2 start svremind-backend"
